name: 'pospos_analytics'
version: '1.0.0'
config-version: 2

profile: 'pospos_analytics'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  pospos_analytics:
    staging:
      +materialized: view
    marts:
      core:
        +materialized: table
      reporting:
        +materialized: table
